kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: aws-pvc
  labels:
     type: aws-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: gp2