 apiVersion: networking.k8s.io/v1beta1
 kind: Ingress
 metadata:
   name: echoserver-ingress
   namespace: ingress-test
   annotations:
     nginx.ingress.kubernetes.io/rewrite-target: /$1
 spec:
   rules:
   - host: hello-world.info
     http:
       paths:
       - path: /
         backend:
           serviceName: echoserver-svc-1
           servicePort: 80
       - path: /v2
         backend:
           serviceName: echoserver-svc-2
           servicePort: 80