apiVersion: v1
kind: Service
metadata:
  name: echoserver-svc-2
  namespace: ingress-test
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: echoserver-2