apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: qa-role
  namespace: qa
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs:
      - list
      - get
      - watch
      - create
      - delete
      - update
      - patch

